# Generated by Django 2.0 on 2018-07-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreationOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorOneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='creationonetoone',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.CreatorOneToOne'),
        ),
    ]
