# Generated by Django 2.0 on 2018-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180720_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTMCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MTMCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mtmcreation',
            name='mtm_creator',
            field=models.ManyToManyField(to='polls.MTMCreator'),
        ),
    ]
